"""
generate_serverconfig.py  -  Generates server/serverconfig.txt from config/server-config.json.

The generated file is what tModLoader reads at startup.
Re-run this (or re-run setup.py) any time you change server-config.json.

Run standalone:
  python scripts/generate_serverconfig.py
"""

import os
import sys
import json

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
BASE_DIR    = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
CONFIG_PATH = os.path.join(BASE_DIR, "config", "server-config.json")
OUTPUT_PATH = os.path.join(BASE_DIR, "server", "serverconfig.txt")
WORLDS_DIR  = os.path.join(BASE_DIR, "worlds")

_DEFAULTS = {
    "server_name" : "My tModLoader Server",
    "port"        : 7777,
    "max_players" : 8,
    "password"    : "",
    "motd"        : "Welcome! Type /help for commands.",
    "world_name"  : "MyWorld",
    "world_size"  : 2,
    "difficulty"  : 1,
    "seed"        : "",
    "auto_create" : True,
    "secure"      : True,
    "language"    : "en-US",
}

# tModLoader's serverconfig.txt format
_TEMPLATE = """\
# serverconfig.txt
# Generated by terraria-tmod-server-kit  |  edit config/server-config.json and re-run setup.py
#
# To apply changes:
#   1. Stop the server (type  exit  in the server console).
#   2. Run  python scripts/generate_serverconfig.py  (or  python scripts/setup.py).
#   3. Start the server again.
#
# NOTE: worldpath and world use absolute paths generated at setup time.
#       If you move this project folder, re-run  python scripts/setup.py.

# ── World ──────────────────────────────────────────────────────────────────

# Full path to the .wld file to load (or auto-create if autocreate=1)
world={world_path}

# Name used when auto-creating a new world
worldname={world_name}

# Folder where world files (.wld) are stored
worldpath={worlds_dir}

# 1 = auto-create the world on first run if the .wld file is missing
# 0 = require the world file to exist (server exits with error if missing)
autocreate={autocreate}

# World size when auto-creating:  1 = small  |  2 = medium  |  3 = large
worldsize={world_size}

# Difficulty when auto-creating:  0 = classic  |  1 = expert  |  2 = master  |  3 = journey
difficulty={difficulty}

# World generation seed (leave blank for a random seed)
seed={seed}

# ── Server ─────────────────────────────────────────────────────────────────

# Name shown in the Terraria server browser
servername={server_name}

# Port the server listens on (Terraria default: 7777)
port={port}

# Maximum number of players allowed at the same time
maxplayers={max_players}

# Server password — leave blank for no password
password={password}

# Message of the day shown to players when they join
motd={motd}

# ── Security ───────────────────────────────────────────────────────────────

# 1 = kick players detected using known exploits / cheat clients
secure={secure}

# Server language
# Choices: en-US  de-DE  it-IT  fr-FR  es-ES  ru-RU  zh-Hans  pt-BR  pl-PL
language={language}

# ── tModLoader ─────────────────────────────────────────────────────────────

# 1 = automatically load all mods from the Mods folder
autoloadmods=1

# NPC network sync rate (10–60).  Lower = fewer packets on slow connections.
npcstream=60

# Process priority: 0=realtime  1=high  2=above-normal  3=normal  4=below-normal  5=idle
priority=1
"""


def load_config():
    """Load user config, falling back to built-in defaults for missing keys."""
    if not os.path.exists(CONFIG_PATH):
        print(f"  WARNING: {CONFIG_PATH} not found — using built-in defaults.")
        return dict(_DEFAULTS)
    with open(CONFIG_PATH, "r", encoding="utf-8") as fh:
        user = json.load(fh)
    # Strip comment keys (they start with _)
    user = {k: v for k, v in user.items() if not k.startswith("_")}
    return {**_DEFAULTS, **user}


def generate(cfg=None):
    """
    Generate server/serverconfig.txt from the given config dict.
    If cfg is None, loads from config/server-config.json.
    Returns the path to the written file.
    """
    if cfg is None:
        cfg = load_config()

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    os.makedirs(WORLDS_DIR, exist_ok=True)

    world_name = str(cfg.get("world_name", "MyWorld")).strip()
    worlds_dir = WORLDS_DIR
    world_path = os.path.join(worlds_dir, f"{world_name}.wld")

    content = _TEMPLATE.format(
        world_path = world_path,
        world_name = world_name,
        worlds_dir = worlds_dir,
        autocreate = "1" if cfg.get("auto_create", True) else "0",
        world_size = int(cfg.get("world_size", 2)),
        difficulty = int(cfg.get("difficulty", 1)),
        seed       = cfg.get("seed", ""),
        server_name= cfg.get("server_name", "My tModLoader Server"),
        port       = int(cfg.get("port", 7777)),
        max_players= int(cfg.get("max_players", 8)),
        password   = cfg.get("password", ""),
        motd       = cfg.get("motd", ""),
        secure     = "1" if cfg.get("secure", True) else "0",
        language   = cfg.get("language", "en-US"),
    )

    with open(OUTPUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(content)

    print(f"  Written: {OUTPUT_PATH}")
    return OUTPUT_PATH


if __name__ == "__main__":
    generate()
    print("serverconfig.txt generated.")
